import json
import re
import shutil
import subprocess
from pathlib import Path

# Characters that are invalid in folder names on Windows/macOS/Linux
INVALID_NAME_CHARS = set('<>:"/\\|?*')

DEFAULT_TODO_TEMPLATE = """# TODO

## High Priority
- [x] (This is a template)
- [ ] (This is a template)

## Medium Priority
- [x] (This is a template)
- [ ] (This is a template)

## Low Priority
- [x] (This is a template)
- [ ] (This is a template)
"""

DEFAULT_ISSUES_TRACKER = {
    "issues": [
        {
            "id": 0,
            "title": "This is a template issue",
            "status": "open/closed",
            "priority": "high/medium/low",
            "created": "YYYY-MM-DD",
            "labels": ["bug/feature/enhancement"],
            "assignee": "username/undifined",
            "description": "This is a template issue description. You can provide more details about the issue here, including steps to reproduce, expected behavior, and any relevant screenshots or logs.",
        }
    ]
}

DEFAULT_PROJECT_METADATA = {
    "project": {
        "name": " ",
        "description": " ",
        "language": " ",
        "version": " ",
        "license": " ",
        "author": " ",
        "created": "YYYY-MM-DD",
    },
    "dependencies": [{"name": " ", "version": " "}, {"name": " ", "version": " "}],
}

DEFAULT_FILE_CONTENTS = {
    "TODO.md": DEFAULT_TODO_TEMPLATE,
    "Issues.json": json.dumps(DEFAULT_ISSUES_TRACKER, indent=2),
    "Project.json": json.dumps(DEFAULT_PROJECT_METADATA, indent=2),
}

DEFAULT_TEMPLATE = {
    "folders": {
        "src": True,  # src is a folder for source code
    },
    "files": {
        "index.html": True,  # index.html is a file for the webUI manager
        "Notes.md": False,  # Notes.md is a file for taking free-form notes
        "Project.json": True,  # Project.json is a file for storing project metadata
        "Issues.json": True,  # Issues.json is a file for tracking issues
        "TODO.md": True,  # TODO.md is a file for tracking tasks
        "README.md": True,  # README.md is a file for project documentation
        ".gitignore": False,
    },
    "init-git-repo": False,
}

DEFAULT_STYLES_CSS = """:root {
    --bg: #0f1115;
    --surface: #1a1d24;
    --surface-hover: #232833;
    --border: #2a2f3a;
    --text: #e8eaed;
    --text-dim: #9aa0ab;
    --accent: #6ea8fe;
}

* {
    box-sizing: border-box;
}

body {
    margin: 0;
    font-family: "Segoe UI", system-ui, -apple-system, sans-serif;
    background: var(--bg);
    color: var(--text);
}

header {
    padding: 2rem 2.5rem 1rem;
    border-bottom: 1px solid var(--border);
}

header h1 {
    margin: 0;
    font-size: 1.6rem;
    font-weight: 600;
}

main {
    padding: 2rem 2.5rem;
    max-width: 900px;
    margin: 0 auto;
}

#projects h2 {
    font-size: 1rem;
    text-transform: uppercase;
    letter-spacing: 0.08em;
    color: var(--text-dim);
    margin-bottom: 1rem;
}

#project-list {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
    gap: 0.9rem;
}

.project-item {
    background: var(--surface);
    border: 1px solid var(--border);
    border-radius: 10px;
    transition: background 0.15s ease, transform 0.15s ease, border-color 0.15s ease;
}

.project-item:hover {
    background: var(--surface-hover);
    border-color: var(--accent);
    transform: translateY(-2px);
}

.project-item a {
    display: block;
    padding: 1.1rem 1.2rem;
    color: var(--text);
    text-decoration: none;
    font-weight: 500;
}

.project-item a::before {
    content: "\\1F4C1";
    margin-right: 0.5rem;
}

.empty-state {
    color: var(--text-dim);
    font-style: italic;
    padding: 1rem 0;
}
"""

DEFAULT_WEBUI_HTML = """<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Just Manage My Projects</title>
        <link rel="stylesheet" href="styles.css" />
    </head>
    <body>
        <header>
            <h1>Just Manage My Projects</h1>
        </header>
        <main>
            <section id="projects">
                <h2>Projects</h2>
                <div id="project-list">
                    <!-- Project items will be dynamically added here -->
                </div>
            </section>
        </main>
        <script>
            // This list is auto-generated by main.py every time a project is
            // created or deleted. Don't edit it by hand — it will be
            // overwritten. Edit main.py's regenerate_webui() if you need to
            // change how it's built.
            function loadProjects() {
                const projectList = document.getElementById("project-list");

                // AUTO-GENERATED-PROJECTS-START
                const projects = [];
                // AUTO-GENERATED-PROJECTS-END

                if (projects.length === 0) {
                    projectList.innerHTML = '<p class="empty-state">No projects yet. Create one with main.py.</p>';
                    return;
                }

                projects.forEach((project) => {
                    // Folder names can contain characters like '#' or '+'
                    // that break a plain href, so each path segment is
                    // percent-encoded before being used as a link target.
                    const encodedPath = project.path
                        .split("/")
                        .map(encodeURIComponent)
                        .join("/");

                    const projectItem = document.createElement("div");
                    projectItem.className = "project-item";
                    const link = document.createElement("a");
                    link.href = `${encodedPath}/index.html`;
                    link.target = "_blank";
                    link.textContent = project.name;
                    projectItem.appendChild(link);
                    projectList.appendChild(projectItem);
                });
            }

            onload = loadProjects;
        </script>
    </body>
</html>
"""


class ProjectManager:
    def __init__(self, projects_dir: Path = Path("./Projects")):
        self.projects_dir = projects_dir
        self.template_path = self.projects_dir / "project_template.json"
        self.template = {}

        self.projects_dir.mkdir(parents=True, exist_ok=True)
        self.load_template()
        self.regenerate_webui()

    # Menu / control flow
    def run(self):
        print("Welcome to Just Manage My Projects!")
        print("What would you like to do?")

        while True:
            choice = self.show_menu()
            if not self.handle_choice(choice):
                break

    def show_menu(self) -> str:
        print(
            "    0. Reload project template\n"
            "    1. Create a new project\n"
            "    2. List existing projects\n"
            "    3. Update a project (If a remote Git repo is present)\n"
            "    4. Delete a project\n"
            "    5. Exit"
        )
        return input("Enter your choice (0-5): ").strip()

    def handle_choice(self, choice: str) -> bool:
        """Returns False when the program should exit."""
        actions = {
            "0": self.reload_template,
            "1": self.create_new_project,
            "2": self.list_existing_projects,
            "3": self.update_project,
            "4": self.delete_project,
        }

        if choice == "5":
            print("Exiting the program. Goodbye!")
            return False

        action = actions.get(choice)
        if action is None:
            print("Invalid choice. Please try again.\n")
        else:
            action()

        return True

    # Template handling
    def reload_template(self):
        if not self.template_path.exists():
            self._create_default_template()
            print("Project template created and reloaded\n")
        else:
            print("Your project template has been reloaded successfully.")

        self.load_template()

    def _create_default_template(self):
        with open(self.template_path, "w", encoding="utf-8") as f:
            json.dump(DEFAULT_TEMPLATE, f, indent=2)

    def load_template(self):
        """Loads the template from disk, creating a default one if missing
        or unreadable. Safe to call anytime (lazy-load)."""
        if not self.template_path.exists():
            self._create_default_template()

        try:
            with open(self.template_path, "r", encoding="utf-8") as f:
                data = json.load(f)
        except (json.JSONDecodeError, OSError) as e:
            print(f"Warning: couldn't read template ({e}). Using defaults.\n")
            data = DEFAULT_TEMPLATE

        # Merge with defaults so missing keys don't silently break things
        self.template = {
            "files": {**DEFAULT_TEMPLATE["files"], **data.get("files", {})},
            "folders": {**DEFAULT_TEMPLATE["folders"], **data.get("folders", {})},
            "init-git-repo": data.get("init-git-repo", False),
        }

        print("Current template settings:\n")
        print(f"folders: {self.template['folders']}")
        print(f"files: {self.template['files']}")
        print(f"init-git-repo: {self.template['init-git-repo']}")
        print()

    # WebUI syncing
    def regenerate_webui(self):
        """Rewrites the auto-generated project list inside WebUI.html so it
        always reflects the folders currently in the Projects directory.
        Recreates WebUI.html and styles.css from defaults if either was
        deleted, the same way project_template.json gets recreated."""
        webui_path = self.projects_dir / "WebUI.html"
        styles_path = self.projects_dir / "styles.css"

        if not styles_path.exists():
            styles_path.write_text(DEFAULT_STYLES_CSS, encoding="utf-8")
            print("styles.css was missing, so it was recreated.\n")

        if not webui_path.exists():
            webui_path.write_text(DEFAULT_WEBUI_HTML, encoding="utf-8")
            print("WebUI.html was missing, so it was recreated.\n")

        project_names = sorted(
            item.name for item in self.projects_dir.iterdir() if item.is_dir()
        )

        if project_names:
            entries = ",\n".join(
                f'                    {{ name: {json.dumps(name)}, path: {json.dumps(name)} }}'
                for name in project_names
            )
            block = f"const projects = [\n{entries},\n                ];"
        else:
            block = "const projects = [];"

        try:
            html = webui_path.read_text(encoding="utf-8")
        except OSError as e:
            print(f"Warning: couldn't read WebUI.html ({e}). Skipping sync.\n")
            return

        pattern = re.compile(
            r"(// AUTO-GENERATED-PROJECTS-START\n)(.*?)(\n\s*// AUTO-GENERATED-PROJECTS-END)",
            re.DOTALL,
        )
        if not pattern.search(html):
            print(
                "Warning: couldn't find the AUTO-GENERATED-PROJECTS markers in "
                "WebUI.html. Skipping sync.\n"
            )
            return

        new_html = pattern.sub(
            lambda m: m.group(1) + "                " + block + m.group(3),
            html,
        )

        try:
            webui_path.write_text(new_html, encoding="utf-8")
        except OSError as e:
            print(f"Warning: couldn't write WebUI.html ({e}).\n")

    # Project actions
    def _is_valid_project_name(self, name: str) -> bool:
        if not name or not name.strip():
            return False
        if name != name.strip():
            # leading/trailing whitespace
            return False
        if any(char in INVALID_NAME_CHARS for char in name):
            return False
        return True

    def create_new_project(self):
        while True:
            project_name = input("Enter the name of the new project: ")

            if not self._is_valid_project_name(project_name):
                print(
                    "Invalid project name. Names can't be empty, "
                    "have leading/trailing spaces, or contain: "
                    f"{' '.join(INVALID_NAME_CHARS)}\n"
                )
                continue

            project_path = self.projects_dir / project_name
            if project_path.exists():
                print(
                    f"A project named '{project_name}' already exists. "
                    "Please choose a different name.\n"
                )
                continue

            break

        # Lazy-load in case the template was never loaded/reloaded
        if not self.template:
            self.load_template()

        project_path.mkdir(parents=True)

        for foldername, should_create in self.template.get("folders", {}).items():
            if should_create:
                (project_path / foldername).mkdir()

        for filename, should_create in self.template.get("files", {}).items():
            if should_create:
                file_path = project_path / filename
                default_content = DEFAULT_FILE_CONTENTS.get(filename)
                if default_content is not None:
                    file_path.write_text(default_content, encoding="utf-8")
                else:
                    file_path.touch()

        if self.template.get("init-git-repo"):
            self._init_git_repo(project_path)

        self.regenerate_webui()
        print(f"Project '{project_name}' created successfully!\n")

    def _init_git_repo(self, project_path: Path):
        if shutil.which("git") is None:
            print("Warning: git is not installed or not on PATH. Skipping git init.\n")
            return

        steps = [
            (["git", "init"], "initialize git repository"),
            (["git", "add", "."], "stage files"),
            (["git", "commit", "-m", "Initial commit"], "create initial commit"),
        ]

        for command, description in steps:
            result = subprocess.run(
                command,
                cwd=project_path,
                capture_output=True,
                text=True,
            )
            if result.returncode != 0:
                print(
                    f"Warning: failed to {description}. Git said:\n{result.stderr.strip()}\n"
                )
                return

    def list_existing_projects(self):
        print("Listing existing projects...")
        projects = [item for item in self.projects_dir.iterdir() if item.is_dir()]

        if not projects:
            print("No projects found.\n")
            return

        for count, item in enumerate(projects, start=1):
            print(f"{count}. {item.name}")
        print()

    def update_project(self):
        # TODO: implement project updating
        print("Update project is not implemented yet — coming soon!\n")

    def delete_project(self):
        project_name = input("Enter the name of the project to delete: ")
        project_path = self.projects_dir / project_name

        if not project_path.exists() or not project_path.is_dir():
            print(f"No project named '{project_name}' found.\n")
            return

        confirmation = (
            input(
                f"Are you sure you want to delete the project '{project_name}'? (y/n): "
            )
            .strip()
            .lower()
        )

        if confirmation == "y":
            shutil.rmtree(project_path)
            self.regenerate_webui()
            print(f"Project '{project_name}' has been deleted.\n")
        else:
            print("Deletion canceled.\n")


def main():
    manager = ProjectManager()
    manager.run()


if __name__ == "__main__":
    main()
